### PR TITLE
Sami/eventlisting

### PR DESCRIPTION
**Pull request by 9samioh**
_Describe your feature here_
- matched event landing page to figma 
- changed bkgd map img to lighter one on orgs and events page
- switched to EventCard component on the events results page
- added trending events and popular near you, scrolls horizonally
- see more button has same functionality as submit
- event landing page now refers to event style sheet
problems: event card click doesn't lead to event page
## Related PRs

_Optional - any related PRs you're waiting on, or PRs that will conflict, etc_

## Migrations

_Optional - if you added anything to the database through migration(s)_

## Screenshots
image
image
image
image

_Required for visual changes_

CC: @claalmve

### CODE REVIEW

**Comment by elixawu** [comment]
hiii looks nice!! i will just give you all the design changes i can think of rn 
- can we actually change the card design back to the other one (vertical picture? :0 the one on the figma) and the gradient in that case would be overlaid on _top_ of any images
- corner rounding on the cards if possible
- can the slogan, "popular", "trending" on landing page match figma font weights 
- on search results page, can the search be added up to the navbar? see figma
- nit: search button on landing page right align w the keyword boxes
really great progress tho i love it

**Comment by elixawu** [comment]
sorry one more thing: 
on the search results page, there needs to be an "apply" button next to the 3 keywords categories. the map becomes a little shorter because of this, see ss for reference
image

**Comment by elixawu** [comment]
sorry ONE more thing - i am actually not sure if this should be left on your PR or a different one (maybe sonja's?) but i will just note it here for now!
i think our page margins/padding on the organization profile (some other pages too, like search results, landing page) are too small & should be a lot wider to be more similar to figma. on org profile we're looking at about 142px padding from leftmost and rightmost sides, though this # might be different depending on screen sizes so it might be helpful to do this by percentages instead

/edit shoot okay LOL i think for this pr it would be good to do implement this on the landing and search result pages, misread this as org profile when it is events listing 

_screenshots_
Screen Shot 2021-05-01 at 1 49 41 AM

**Comment by claalmve** [comment]
This PR looks great @9samioh ! Thanks for pushing so quickly to get event cards ready for demos, they were incredible to see! I'm pushing this PR into the codebase for now, but please address @elixawu 's comments above in a separate PR off of main later!

**Pull request merged**
