### PR TITLE
Implementing basic tables for Next-Auth implementation

### PR DESCRIPTION
**Pull request by claalmve**
Building basic tables for Next-Auth implementation.

## Related PRs

_Optional - any related PRs you're waiting on, or PRs that will conflict, etc_

## Migrations

_Optional - if you added anything to the database through migration(s)_

## Screenshots

_Required for visual changes_

CC: @kwfk

### CODE REVIEW

**Review by kwfk — CHANGES_REQUESTED** [review]
please add to Migrations section in PR

rebase with main:
- you will run into a conflict in `orgs/[id].tsx`
- just select current changes for all
- then run `git rebase --continue`

you may need to run your migrations again after rebasing
for safety simply drop you db and re-run all migrations with `yarn db:update`

**Comment by claalmve** [comment]
> please add to Migrations section in PR
> 
> rebase with main:
> 
> * you will run into a conflict in `orgs/[id].tsx`
> * just select current changes for all
> * then run `git rebase --continue`
> 
> you may need to run your migrations again after rebasing
> for safety simply drop you db and re-run all migrations with `yarn db:update`

Should be all set! For some reason, I think more changes are being tracked in the PR than what I changed, but conflicts across files should be resolved now.

**Comment by kwfk** [comment]
> > please add to Migrations section in PR
> > rebase with main:
> > 
> > * you will run into a conflict in `orgs/[id].tsx`
> > * just select current changes for all
> > * then run `git rebase --continue`
> > 
> > you may need to run your migrations again after rebasing
> > for safety simply drop you db and re-run all migrations with `yarn db:update`
> 
> Should be all set! For some reason, I think more changes are being tracked in the PR than what I changed, but conflicts across files should be resolved now.

if you rebase correctly, github shouldn't be tracking the changes that you didn't make...

**Review by kwfk — APPROVED** [review]
if you want to see the branch locally run `git reset --hard origin/calvin/next-auth` because i force pushed with my rebase

remember that when you add something in your migration to always add the revert in the `drop` function
also when you get a types doesn't exist error from typescript, look for a `@types/[package-name]` and add the package

**Comment by claalmve** [comment]
> if you want to see the branch locally run `git reset --hard origin/calvin/next-auth` because i force pushed with my rebase
> 
> remember that when you add something in your migration to always add the revert in the `drop` function
> also when you get a types doesn't exist error from typescript, look for a `@types/[package-name]` and add the package

Gotcha! I forgot about adding that into my migrations, I'll definitely remember for the future :D Thanks Fred!

**Pull request merged**
