### PR TITLE
Bryanna/event cards edited

### PR DESCRIPTION
**Pull request by bry-gavino**
Fixed css styling to match Figma dimensions.
Same feature as branch "bryanna/event-cards".

## Screenshots

Screen Shot 2021-04-30 at 10 44 36 PM

CC: @claalmve

### CODE REVIEW

**Comment by elixawu** [comment]
aaaaaa i really like! is it possible to have a bit more spacing btwn date - title - link? like just a TINY tiny bit and it'd be perfect (this is really a nit though so if you have more important things then no worries)

**Comment by bry-gavino** [comment]
> aaaaaa i really like! is it possible to have a bit more spacing btwn date - title - link? like just a TINY tiny bit and it'd be perfect (this is really a nit though so if you have more important things then no worries)

hi hi hi ty!! I added a bit more spacing but lmk if you want me to edit it in anyway even more :)

**Review by elixawu — COMMENTED** [review]
lgtm!!

**Comment by claalmve** [comment]
Closing in favor of #121 with same changes but less merge conflicts. Nice work Bry!

**Pull request closed without merging**
